const jobs=[
{id:1,title:"Agent de sécurité",country:"Belgique",city:"Bruxelles",type:"Sécurité",contract:"Temps plein",description:"Poste d'agent de sécurité en Belgique.",requirements:"Sérieux, ponctuel et expérience en sécurité."},
{id:2,title:"Serveur",country:"Belgique",city:"Bruxelles",type:"Hôtellerie",contract:"Temps plein",description:"Poste de serveur dans un établissement hôtelier.",requirements:"Expérience en restauration et bon contact avec les clients."},
{id:3,title:"Réceptionniste",country:"Belgique",city:"Liège",type:"Hôtellerie",contract:"Temps plein",description:"Accueil des clients et gestion de la réception.",requirements:"Français et expérience en réception."},
{id:4,title:"Préparateur de commandes",country:"France",city:"Lille",type:"Logistique",contract:"Temps plein",description:"Préparation et organisation des commandes dans un entrepôt.",requirements:"Ponctualité, rigueur et bonne condition physique."},
{id:5,title:"Employé agricole",country:"Espagne",city:"Valence",type:"Agriculture",contract:"Saisonnier",description:"Travail saisonnier dans une exploitation agricole.",requirements:"Motivation, disponibilité et capacité à travailler en équipe."},
{id:6,title:"Agent d'entretien",country:"Allemagne",city:"Berlin",type:"Entretien",contract:"Temps plein",description:"Entretien des espaces communs d'un établissement.",requirements:"Sérieux, autonomie et sens de l'organisation."}];
const $=id=>document.getElementById(id),getUser=()=>JSON.parse(localStorage.getItem("wt_user")||"null"),getApps=()=>JSON.parse(localStorage.getItem("wt_apps")||"[]");
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function populateFilters(){const cs=[...new Set(jobs.map(j=>j.country))].sort(),ts=[...new Set(jobs.map(j=>j.type))].sort();$("countryFilter").innerHTML='<option value="">Tous les pays</option>'+cs.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join("");$("typeFilter").innerHTML='<option value="">Tous les secteurs</option>'+ts.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join("")}
function displayJobs(list=jobs){$("resultsCount").textContent=`${list.length} offre${list.length>1?"s":""}`;if(!list.length){$("jobs").innerHTML='<div class="empty-state"><h3>Aucune offre trouvée</h3><p>Essayez un autre filtre.</p></div>';return}$("jobs").innerHTML=list.map(j=>`<article class="job-card"><h3>${esc(j.title)}</h3><div class="job-meta"><span>📍 ${esc(j.city)}, ${esc(j.country)}</span><span>💼 ${esc(j.type)}</span><span>🕐 ${esc(j.contract)}</span></div><p>${esc(j.description)}</p><button onclick="showJob(${j.id})">Voir les détails →</button></article>`).join("")}
function showJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;$("jobs").innerHTML=`<article class="job-card"><span class="eyebrow">OFFRE D'EMPLOI</span><h2>${esc(j.title)}</h2><div class="job-meta"><span>📍 ${esc(j.city)}, ${esc(j.country)}</span><span>💼 ${esc(j.type)}</span><span>🕐 ${esc(j.contract)}</span></div><div class="job-description"><h3>Description</h3><p>${esc(j.description)}</p><h3>Conditions</h3><p>${esc(j.requirements)}</p></div><button onclick="applyJob(${j.id})">📩 Postuler</button><button onclick="resetView()" class="back-button">← Retour</button></article>`;$("offres").scrollIntoView({behavior:"smooth"})}
function applyJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;if(!getUser()){openAccount("login");return}const u=getUser();let a=getApps();if(a.some(x=>x.jobId===id&&x.email===u.email)){alert("Vous avez déjà postulé à cette offre.");return}a.push({jobId:id,title:j.title,city:j.city,country:j.country,email:u.email,date:new Date().toLocaleDateString("fr-FR")});localStorage.setItem("wt_apps",JSON.stringify(a));alert("Candidature enregistrée dans votre espace.");openAccount("dashboard")}
function openAccount(mode){const u=getUser();if(u){renderDashboard();$("compte").scrollIntoView({behavior:"smooth"});return}renderAuth(mode||"register");$("compte").scrollIntoView({behavior:"smooth"})}
function renderAuth(mode="register"){$("account").innerHTML=`<div class="account-card"><span class="eyebrow">ESPACE CANDIDAT</span><h2>${mode==="login"?"🔐 Connexion":"👤 Créer mon compte"}</h2><p>${mode==="login"?"Connectez-vous pour gérer votre profil et vos candidatures.":"Créez un profil pour postuler et enregistrer votre CV."}</p><form class="application-form" onsubmit="${mode==="login"?"login(event)":"register(event)"}"><input id="authName" type="text" placeholder="Nom complet" ${mode==="login"?"style="display:none"": "required"}><input id="authEmail" type="email" placeholder="Adresse e-mail" required><input id="authPassword" type="password" placeholder="Mot de passe" minlength="6" required><button type="submit">${mode==="login"?"Se connecter":"Créer mon compte"}</button></form><button class="link-button" onclick="renderAuth('${mode==="login"?"register":"login"}')">${mode==="login"?"Créer un compte":"J'ai déjà un compte"}</button><p class="demo-note">Mode prototype : les données sont stockées uniquement dans ce navigateur.</p></div>`}
function register(e){e.preventDefault();const name=$("authName").value.trim(),email=$("authEmail").value.trim().toLowerCase(),password=$("authPassword").value;if(password.length<6)return alert("Le mot de passe doit contenir au moins 6 caractères.");localStorage.setItem("wt_user",JSON.stringify({name,email,password}));renderDashboard()}
function login(e){e.preventDefault();const email=$("authEmail").value.trim().toLowerCase(),password=$("authPassword").value,u=getUser();if(!u||u.email!==email||u.password!==password)return alert("E-mail ou mot de passe incorrect.");renderDashboard()}
function renderDashboard(){$("account").innerHTML="";const u=getUser(),apps=getApps().filter(a=>a.email===u.email);$("account").innerHTML=`<div class="account-card"><div class="account-top"><div><span class="eyebrow">MON COMPTE</span><h2>👋 Bonjour ${esc(u.name)}</h2><p>${esc(u.email)}</p></div><button class="back-button" onclick="logout()">Se déconnecter</button></div><div class="profile-grid"><div><h3>📄 Mon CV</h3><input type="file" id="cvFile" accept=".pdf,.doc,.docx" onchange="saveCV(event)"><p id="cvStatus" class="small-note"></p></div><div><h3>📊 Mes candidatures</h3><strong class="big-number">${apps.length}</strong><p class="small-note">candidature(s) enregistrée(s)</p></div></div><div class="applications-list"><h3>Historique</h3>${apps.length?apps.map(a=>`<div class="application-row"><strong>${esc(a.title)}</strong><span>📍 ${esc(a.city)}, ${esc(a.country)}</span><small>${esc(a.date)}</small></div>`).join(""):'<p class="small-note">Aucune candidature pour le moment.</p>'}</div></div>`;const cv=localStorage.getItem("wt_cv_name");if(cv)$("cvStatus").textContent="CV enregistré : "+cv}
function saveCV(e){const f=e.target.files[0];if(!f)return;if(f.size>5*1024*1024)return alert("Le CV doit faire moins de 5 Mo.");localStorage.setItem("wt_cv_name",f.name);$("cvStatus").textContent="CV sélectionné : "+f.name+" (prototype local)"}
function logout(){localStorage.removeItem("wt_user");localStorage.removeItem("wt_cv_name");renderAuth("login")}
function searchJobs(){const t=$("search").value.trim().toLowerCase(),c=$("countryFilter").value,ty=$("typeFilter").value;displayJobs(jobs.filter(j=>(!t||[j.title,j.country,j.city,j.type,j.description].some(v=>v.toLowerCase().includes(t)))&&(!c||j.country===c)&&(!ty||j.type===ty)))}
function resetView(){$("search").value="";$("countryFilter").value="";$("typeFilter").value="";displayJobs(jobs);$("offres").scrollIntoView({behavior:"smooth"})}
document.addEventListener("DOMContentLoaded",()=>{populateFilters();displayJobs();if(getUser())renderDashboard()});