const jobs=[{id:1,title:"Agent de sécurité",country:"Belgique",city:"Bruxelles",type:"Sécurité",contract:"Temps plein",description:"Poste d'agent de sécurité en Belgique.",requirements:"Sérieux, ponctuel et expérience en sécurité."},{id:2,title:"Serveur",country:"Belgique",city:"Bruxelles",type:"Hôtellerie",contract:"Temps plein",description:"Poste de serveur dans un établissement hôtelier.",requirements:"Expérience en restauration et bon contact avec les clients."},{id:3,title:"Réceptionniste",country:"Belgique",city:"Liège",type:"Hôtellerie",contract:"Temps plein",description:"Accueil des clients et gestion de la réception.",requirements:"Français et expérience en réception."},{id:4,title:"Préparateur de commandes",country:"France",city:"Lille",type:"Logistique",contract:"Temps plein",description:"Préparation et organisation des commandes dans un entrepôt.",requirements:"Ponctualité, rigueur et bonne condition physique."},{id:5,title:"Employé agricole",country:"Espagne",city:"Valence",type:"Agriculture",contract:"Saisonnier",description:"Travail saisonnier dans une exploitation agricole.",requirements:"Motivation, disponibilité et capacité à travailler en équipe."},{id:6,title:"Agent d'entretien",country:"Allemagne",city:"Berlin",type:"Entretien",contract:"Temps plein",description:"Entretien des espaces communs d'un établissement.",requirements:"Sérieux, autonomie et sens de l'organisation."}];
const $=id=>document.getElementById(id);
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function populateFilters(){const cs=[...new Set(jobs.map(j=>j.country))].sort(),ts=[...new Set(jobs.map(j=>j.type))].sort();$("countryFilter").innerHTML='<option value="">Tous les pays</option>'+cs.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join("");$("typeFilter").innerHTML='<option value="">Tous les secteurs</option>'+ts.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join("")}
function displayJobs(list=jobs){$("resultsCount").textContent=`${list.length} offre${list.length>1?"s":""}`;if(!list.length){$("jobs").innerHTML='<div class="empty-state"><h3>Aucune offre trouvée</h3><p>Essayez un autre métier, une autre ville ou un autre pays.</p></div>';return}$("jobs").innerHTML=list.map(j=>`<article class="job-card"><h3>${esc(j.title)}</h3><div class="job-meta"><span>📍 ${esc(j.city)}, ${esc(j.country)}</span><span>💼 ${esc(j.type)}</span><span>🕐 ${esc(j.contract)}</span></div><p>${esc(j.description)}</p><button onclick="showJob(${j.id})">Voir les détails →</button></article>`).join("")}
function showJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;$("jobs").innerHTML=`<article class="job-card"><span class="eyebrow">OFFRE D'EMPLOI</span><h2>${esc(j.title)}</h2><div class="job-meta"><span>📍 ${esc(j.city)}, ${esc(j.country)}</span><span>💼 ${esc(j.type)}</span><span>🕐 ${esc(j.contract)}</span></div><div class="job-description"><h3>Description</h3><p>${esc(j.description)}</p><h3>Conditions</h3><p>${esc(j.requirements)}</p></div><button onclick="applyJob(${j.id})">📩 Postuler</button><button onclick="resetView()" class="back-button">← Retour aux offres</button></article>`;$("offres").scrollIntoView({behavior:"smooth"})}
function applyJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;$("jobs").innerHTML=`<article class="job-card"><span class="eyebrow">CANDIDATURE</span><h2>📩 ${esc(j.title)}</h2><p>📍 ${esc(j.city)}, ${esc(j.country)}</p><form class="application-form" onsubmit="sendApplication(event)"><input type="text" id="name" placeholder="Votre nom complet" required><input type="email" id="email" placeholder="Votre adresse e-mail" required><input type="tel" id="phone" placeholder="Votre numéro de téléphone" required><textarea id="message" placeholder="Message au recruteur"></textarea><div><button type="submit">Envoyer ma candidature</button><button type="button" onclick="showJob(${j.id})" class="back-button">← Retour</button></div></form></article>`;$("offres").scrollIntoView({behavior:"smooth"})}
function sendApplication(e){e.preventDefault();const n=$("name").value.trim(),em=$("email").value.trim(),p=$("phone").value.trim();if(!n||!em||!p)return;$("jobs").innerHTML=`<div class="job-card"><h2>✅ Candidature enregistrée</h2><p>Merci <strong>${esc(n)}</strong>. Votre candidature est prête à être transmise au recruteur.</p><p>📧 E-mail : ${esc(em)}</p><p>📱 Téléphone : ${esc(p)}</p><button onclick="resetView()">← Retour aux offres</button></div>`;$("offres").scrollIntoView({behavior:"smooth"})}
function searchJobs(){const t=$("search").value.trim().toLowerCase(),c=$("countryFilter").value,ty=$("typeFilter").value;displayJobs(jobs.filter(j=>(!t||[j.title,j.country,j.city,j.type,j.description].some(v=>v.toLowerCase().includes(t)))&&(!c||j.country===c)&&(!ty||j.type===ty)))}
function resetView(){$("search").value="";$("countryFilter").value="";$("typeFilter").value="";displayJobs(jobs);$("offres").scrollIntoView({behavior:"smooth"})}
document.addEventListener("DOMContentLoaded",()=>{populateFilters();displayJobs()});